AWS_3/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^/login/$', 'django.contrib.auth.views.login'),
    url(r'', include('reminder.urls')),
    url(r'^captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reminder/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^aboutus/$', views.about, name='about'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/settings/$', views.profile_settings, name='settings'),
    url(r'^profile/custom_category/$',
        views.custom_category, name='custom_category'),
    url(r'^profile/premade_action/$', views.premade_action, name='premade_action'),
    url(r'^profile/create_task/$', views.create_task),
    url(r'^profile/stat_init/$', views.stat_init),
    url(r'^profile/edit_task_init/$', views.edit_task_init),
    url(r'^profile/delete_task/$', views.delete_task),
    url(r'^profile/acknowledge/$', views.acknowledge),
    url(r'^profile/acknowledge_init/$', views.acknowledge_init),
    url(r'^profile/premade_action/form_category/$', views.form_category),
    url(r'^profile/premade_action/form_name/$', views.form_name),
]

reminder/models.py
from django.db import models
from django.forms import ModelForm
from django.utils import timezone
from django.contrib.auth.models import User
import datetime
from reminder.choices import IMPORTANCE_CHOICES, DATE_CHOICES


class UserProfile(models.Model):
    """Extends the User model and adds some additional variables"""
    user = models.OneToOneField(User)

    email_alerts = models.BooleanField(default=True)
    join_date = models.DateTimeField(default=timezone.now)
    score = models.score = models.IntegerField(default=0)
    en_notifications = models.BooleanField(default=True)

    def __unicode__(self):
        return self.user.username


class Task(models.Model):
    """Individual task model.  Linked to a user."""
    user = models.ForeignKey(User)

    name = models.CharField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)
    """Not included in the profile, only in the settings"""
    due_date = models.DateTimeField(default=timezone.now)
    last_date = models.DateTimeField(default=timezone.now)
    frequency_int = models.IntegerField(default=1)
    frequency_choice = models.IntegerField(default=1)
    category = models.IntegerField(default=1)
    """1 = General, 2 = Hygiene/Fitness, 3 = Maintenance, 4 = School/Business,
       5 = Social
    """
    importance = models.IntegerField(default=3, choices=IMPORTANCE_CHOICES)
    """1 = Trivial, 2 = Minor, 3 = Moderate, 4 = Significant, 5 = Critical"""
    past_due = models.BooleanField(default=True)
    time_delta = models.FloatField(default=0.0)
    choice = models.IntegerField(default=0)
    """0 = smartTRACK, 1 = date, 2 = frequency"""
    acknowledge_total = models.IntegerField(default=0)
    notified = models.BooleanField(default=False)

    """smartTRACK settings go here"""
    en_smartTRACK = models.IntegerField(default=0)
    """0 = disabled, 1 = enabled but tracking not ready,
       2 = enabled and tracking ready
    """
    omit_total = models.IntegerField(default=0)

    def importance_formatted(self):
        temp = self.importance

        if temp == 1:
            display = 'Trivial'
        elif temp == 2:
            display = 'Minor'
        elif temp == 3:
            display = 'Moderate'
        elif temp == 4:
            display = 'Significant'
        elif temp == 5:
            display = 'Critical'
        else:
            display = 'ERROR'

        return display

    def frequency_formatted(self):
        choice = self.frequency_choice
        integer = self.frequency_int
        tracking = self.en_smartTRACK

        if tracking == 1:
            return '-'
        else:
            if choice == 4:
                if integer == 1:
                    integer = ''
                    end = ''
                else:
                    integer = '{} '.format(integer)
                    end = 's'

                return 'Every {}month{}'.format(integer, end)
            else:
                val = int(self.time_delta)

                weeks = int(val / 604800)
                days = int((val - (weeks * 604800)) / 86400)
                hours = int((val - (weeks * 604800) - (days * 86400)) / 3600)
                weeks_comma = ', '
                days_comma = ', '

                if val == 0:
                    phrase = ''
                else:
                    if days == 0 and hours == 0:
                        weeks_comma = ''

                    if hours == 0:
                        days_comma = ''
                        hours = ''
                    elif hours == 1:
                        if days != 0 or weeks != 0:
                            hours = '{} hour'.format(hours)
                        else:
                            hours = 'hour'
                    else:
                        hours = '{} hours'.format(hours)

                    if days == 0:
                        days = ''
                    elif days == 1:
                        if weeks != 0 or days != 0:
                            days = '{} day{}'.format(days, days_comma)
                        else:
                            days = 'day{}'.format(days_comma)
                    else:
                        days = '{} days{}'.format(days, days_comma)

                    if weeks == 0:
                        weeks = ''
                    elif weeks == 1:
                        if days != 0 or hours != 0:
                            weeks = '{} week{}'.format(weeks, weeks_comma)
                        else:
                            weeks = 'week{}'.format(weeks_comma)
                    else:
                        weeks = '{} weeks{}'.format(weeks, weeks_comma)

                    phrase = 'Every {}{}{}'.format(weeks, days, hours)

                return phrase

    def choice_formatted(self):
        choice = self.choice

        if choice == 0:
            return 'SmartTRACK'
        elif choice == 1:
            return 'Date'
        else:
            return 'Frequency'

    def __str__(self):
        return self.name


class History(models.Model):
    """Task Acknowledge History"""
    task = models.ForeignKey(Task)
    acknowledge_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        month = self.acknowledge_date.month
        if month < 10:
            month = '0{}'.format(month)

        day = self.acknowledge_date.day
        if day < 10:
            day = '0{}'.format(day)

        hour = self.acknowledge_date.hour
        if hour < 10:
            hour = '0{}'.format(hour)

        minute = self.acknowledge_date.minute
        if minute < 10:
            minute = '0{}'.format(minute)

        return '{}{}{}_{}{}'.format(self.acknowledge_date.year, month, day, hour, minute)


class Custom(models.Model):
    """Custom Category"""
    user = models.ForeignKey(User)

    name = models.CharField(max_length=50)
    value = models.IntegerField(default=6)

    def __str__(self):
        return self.name

reminder/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.db.models import Q
from itertools import chain
from reminder.utilities import smartTRACK, validate
from .models import UserProfile, Task, History, Custom
from .forms import UserForm, PasswordForm
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.decorators.cache import cache_control
from django.http import JsonResponse
from django.core.mail import send_mail
from django.conf import settings
from dateutil.relativedelta import relativedelta
import random
import datetime
import math
import pytz


def home(request):
    """Home Page.  Display a brief message.  Should  be changed to an info
       page with sample task names/list
    """
    template = Task.objects.all().filter(user_id__gt=1).order_by('?')[:9]

    return render(request, 'reminder/home.html', {'template': template})


def acknowledge_init(request):
    """Acknowledge Initialization"""
    response = {}
    task = request.user.task_set.get(pk=int(request.POST.get('id')))

    response['last_year'] = task.last_date.year
    response['last_month'] = task.last_date.month
    response['last_day'] = task.last_date.day
    response['last_hour'] = task.last_date.hour
    response['last_minute'] = task.last_date.minute

    response['due_year'] = task.due_date.year
    response['due_month'] = task.due_date.month
    response['due_day'] = task.due_date.day
    response['due_hour'] = task.due_date.hour
    response['due_minute'] = task.due_date.minute

    response['name'] = task.name
    response['en_SmartTRACK'] = task.en_smartTRACK

    return JsonResponse(response)


def stat_init(request):
    """Edit Task function.  Called when a table row is clicked."""
    response = {}
    task = request.user.task_set.get(pk=int(request.POST.get('id')))
    offset = int(int(request.POST.get('offset')) / 60)

    # Populate the form's initial values with the correct task
    response['name'] = task.name
    response['en_SmartTRACK'] = task.en_smartTRACK
    response['choice'] = task.choice
    response['total'] = task.acknowledge_total
    response['track'] = task.choice_formatted()
    response['frequency'] = task.frequency_formatted()
    response['category'] = task.category
    response['importance'] = task.importance
    response['freq_int'] = task.frequency_int
    response['freq_choice'] = task.frequency_choice

    response['created_year'] = task.created_date.year
    response['created_month'] = task.created_date.month
    response['created_day'] = task.created_date.day
    response['created_hour'] = task.created_date.hour
    response['created_minute'] = task.created_date.minute

    response['last_year'] = task.last_date.year
    response['last_month'] = task.last_date.month
    response['last_day'] = task.last_date.day
    response['last_hour'] = task.last_date.hour
    response['last_minute'] = task.last_date.minute

    response['due_year'] = task.due_date.year
    response['due_month'] = task.due_date.month
    response['due_day'] = task.due_date.day
    response['due_hour'] = task.due_date.hour
    response['due_minute'] = task.due_date.minute

    due_date = task.due_date + datetime.timedelta(hours=0-offset)
    due_time = int(task.due_date.hour - offset)

    if due_time < 0:
        due_time += 24

    response['due_date'] = '{}/{}/{}'.format(
        due_date.month, due_date.day, due_date.year)
    response['due_time'] = due_time

    return JsonResponse(response)


def edit_task_init(request):
    """Edit Task function.  Called when a table row is clicked."""
    response = {}
    task = request.user.task_set.get(pk=int(request.POST.get('id')))

    # Populate the form's initial values with the correct task
    response['name'] = task.name
    response['importance'] = task.importance
    response['en_SmartTRACK'] = task.en_smartTRACK
    response['choice'] = task.choice

    response['created_year'] = task.created_date.year
    response['created_month'] = task.created_date.month
    response['created_day'] = task.created_date.day
    response['created_hour'] = task.created_date.hour
    response['created_minute'] = task.created_date.minute

    if task.choice == 1:
        offset = int(int(request.POST.get('offset')) / 60)

        due_date = task.due_date + datetime.timedelta(hours=0-offset)
        due_time = int(task.due_date.hour - offset)

        if due_time < 0:
            due_time += 24

        response['due_date'] = '{}/{}/{}'.format(
            due_date.month, due_date.day, due_date.year)
        response['due_time'] = due_time
    elif task.choice == 2:
        response['frequency_int'] = task.frequency_int
        response['frequency_choice'] = task.frequency_choice

    response['category'] = task.category

    return JsonResponse(response)


def acknowledge(request):
    """Acknowledge function.  Called when 'Yes' is pressed on the acknowledge
       pop-up
    """
    response = {}
    task = request.user.task_set.get(pk=int(request.POST.get('id')))

    temp_time = timezone.now() + datetime.timedelta(seconds=1)
    formatted_time = timezone.now() - datetime.timedelta(seconds=timezone.now().second,
                                                         microseconds=timezone.now().microsecond)
    freq_int = task.frequency_int
    freq_choice = task.frequency_choice
    choice = task.choice

    if request.POST.get('type') == 'button':
        due_list = request.user.task_set.exclude(id=task.id).filter(category=task.category).order_by('due_date')

        position_start = 0

        for temp_task in due_list:
            if task.due_date < temp_task.due_date:
                break

            position_start += 1

    if temp_time >= task.due_date:
        if task.past_due:
            score = -5 - (task.importance * 5)
            request.user.userprofile.score += score
            request.user.userprofile.save()
            task.past_due = 0
            response['score'] = score
        else:
            response['score'] = 0

        if request.POST.get('type') == 'button':
            task.past_due = 1
            task.last_date = formatted_time

            if choice == 0:
                if request.POST.get('omit') != 'true':
                    # create a new history point if not omitted
                    task.history_set.create(acknowledge_date=formatted_time)

                    smartTRACK(task, formatted_time)
                    task.en_smartTRACK = 2
            elif choice == 1:
                task.due_date = formatted_time + \
                    datetime.timedelta(seconds=task.time_delta)
                duration = int(task.time_delta / 3600)
            elif choice == 2:
                if freq_choice == 1:
                    task.due_date = formatted_time + \
                        datetime.timedelta(hours=freq_int)
                elif freq_choice == 2:
                    task.due_date = formatted_time + \
                        datetime.timedelta(hours=freq_int * 24)
                elif freq_choice == 3:
                    task.due_date = formatted_time + \
                        datetime.timedelta(hours=freq_int * 24 * 7)
                elif freq_choice == 4:
                    task.due_date = formatted_time + \
                        relativedelta(months=freq_int)
                elif freq_choice == 5:
                    task.due_date = formatted_time + \
                        relativedelta(months=freq_int * 12)

            task.acknowledge_total += 1

    elif temp_time < task.due_date:
        duration = 0

        if choice == 0:
            if request.POST.get('omit') != 'true':
                # create a new history point if not omitted
                task.history_set.create(acknowledge_date=formatted_time)

                smartTRACK(task, formatted_time)
                task.en_smartTRACK = 2
        elif choice == 1:
            task.due_date = formatted_time + \
                datetime.timedelta(seconds=task.time_delta)
            duration = int(task.time_delta / 3600)
        elif choice == 2:
            if freq_choice == 1:
                duration = freq_int
                task.due_date = formatted_time + \
                    datetime.timedelta(hours=duration)
            elif freq_choice == 2:
                duration = freq_int * 24
                task.due_date = formatted_time + \
                    datetime.timedelta(hours=duration)
            elif freq_choice == 3:
                duration = freq_int * 24 * 7
                task.due_date = formatted_time + \
                    datetime.timedelta(hours=duration)
            elif freq_choice == 4:
                duration = 24 * 30.4375
                task.due_date = formatted_time + relativedelta(months=freq_int)
            elif freq_choice == 5:
                duration = 24 * 365.25
                task.due_date = formatted_time + \
                    relativedelta(months=freq_int * 12)

        task.acknowledge_total += 1
        task.notified = False

        score = int(math.sqrt(duration) *
                    (((task.importance * task.importance) / 50) + 1))

        if score > 100:
            score = 100

        request.user.userprofile.score += score
        request.user.userprofile.save()

        response['score'] = score
        task.past_due = 1
        task.last_date = formatted_time

    task.save()

    if request.POST.get('type') == 'button':
        category_list = request.user.task_set.filter(category=task.category)
        response['changed'] = False

        if category_list.__len__() > 1:
            due_list = request.user.task_set.exclude(id=task.id).filter(category=task.category).order_by('due_date')

            position = 0

reminder/templates/forms/premade.html
                    <div id="div_id_name">
                        <label for="id_name">Name*</label>
                        <input id="id_name" maxlength="50" name="name" type="text" placeholder="Name" disabled>
                    </div>

                    <div data-role="fieldcontain"  id="div_radio" class="radiogroup">
                        <fieldset data-role="controlgroup" data-type="horizontal">
                            <legend>How should the action item be monitored?*</legend>
                                <input type="radio" name="radio-choice" id="id_choice_smartTRACK" value="1" checked="checked" disabled/>
                                <label for="id_choice_smartTRACK">SmartTRACK</label>

                                <input type="radio" name="radio-choice" id="id_choice_date" value="2" disabled/>
                                <label for="id_choice_date">Date</label>

                                <input type="radio" name="radio-choice" id="id_choice_frequency" value="3" disabled/>
                                <label for="id_choice_frequency">Frequency</label>
                        </fieldset>
                    </div>

                    <div id="div_choice_date" style="display: none;">
                        <div id="div_id_due_date">
                            <label for="id_due_date">Date*</label>
                            <input type="text" id="id_due_date" name="due_date" data-role="date" data-inline="true" placeholder="Date" disabled>
                        </div>
                        <div id="div_id_due_time">
                            <label for="id_due_time">Time*</label>
                            <select id="id_due_time" name="due_time" disabled>
                                <option value="0">12:00 AM</option>
                                <option value="1">1:00 AM</option>
                                <option value="2">2:00 AM</option>
                                <option value="3">3:00 AM</option>
                                <option value="4">4:00 AM</option>
                                <option value="5">5:00 AM</option>
                                <option value="6">6:00 AM</option>
                                <option value="7">7:00 AM</option>
                                <option value="8">8:00 AM</option>
                                <option value="9">9:00 AM</option>
                                <option value="10">10:00 AM</option>
                                <option value="11">11:00 AM</option>
                                <option value="12" selected='selected'>12:00 PM</option>
                                <option value="13">1:00 PM</option>
                                <option value="14">2:00 PM</option>
                                <option value="15">3:00 PM</option>
                                <option value="16">4:00 PM</option>
                                <option value="17">5:00 PM</option>
                                <option value="18">6:00 PM</option>
                                <option value="19">7:00 PM</option>
                                <option value="20">8:00 PM</option>
                                <option value="21">9:00 PM</option>
                                <option value="22">10:00 PM</option>
                                <option value="23">11:00 PM</option>
                            </select>
                        </div>
                    </div>

                    <div id="div_choice_frequency" style="display: none;">
                        <div id="div_id_frequency_int">
                            <label for="id_frequency_int">Once Every*</label>
                            <input id="id_frequency_int" min="1" name="frequency_int" type="number" placeholder="Once Every" onkeypress="return isNumber(event)" disabled>
                        </div>
                        <div id="div_id_frequency_choice">
                            <label for="id_frequency_choice">Frequency*</label>
                            <select id="id_frequency_choice" name="frequency_choice" disabled>
                                <option value="1">Hour(s)</option>
                                <option value="2" selected='selected'>Day(s)</option>
                                <option value="3">Week(s)</option>
                                <option value="4">Month(s)</option>
                                <option value="5">Year(s)</option>
                            </select>
                        </div>
                    </div>

                    <div id="div_id_importance">
                        <label for="id_importance">Importance</label>
                        <select id="id_importance" name="importance" disabled>
                            <option value="1">Trivial</option>
                            <option value="2">Minor</option>
                            <option value="3" selected='selected'>Moderate</option>
                            <option value="4">Significant</option>
                            <option value="5">Critical</option>
                        </select>
                    </div>

                    <div id="div_id_category">
                        <label for="id_category">Category*</label>
                        <select id="id_category" name="category" disabled>
                            {% for category in category_list %}<option value="{{ category.value }}"{% if category.name == 'General' %} selected='selected'{% endif %}>{{ category }}</option>
                            {% endfor %}
                        </select>
                    </div>

reminder/templates/forms/task.html
                    <div id="created_date"></div>

                    <div id="div_id_name" class="form-group">
                        <label for="id_name">Name*</label>
                        <input id="id_name" maxlength="50" name="name" type="text" class="form-control" placeholder="Name">
                    </div>

                    <div data-role="fieldcontain"  id="div_id_radio" class="radiogroup">
                        <fieldset data-role="controlgroup" data-type="horizontal">
                            <legend>How should the action item be monitored?*</legend>
                                <input type="radio" name="radio-choice" id="id_choice_smartTRACK" value="0" checked="checked"/>
                                <label for="id_choice_smartTRACK">SmartTRACK</label>

                                <input type="radio" name="radio-choice" id="id_choice_date" value="1"/>
                                <label for="id_choice_date">Date</label>

                                <input type="radio" name="radio-choice" id="id_choice_frequency" value="2"/>
                                <label for="id_choice_frequency">Frequency</label>
                        </fieldset>
                    </div>

                    <div id="div_choice_date" class="form-group" style="display: none;">
                        <div id="div_id_due_date" class="form-group">
                            <label for="id_due_date">Date* (E.g.  5/23/2018)</label>
                            <input type="text" id="id_due_date" name="due_date" class="form-control form-wider" data-role="date" data-inline="true" placeholder="Date">
                        </div>
                        <div id="div_id_due_time" class="ui-field-contain">
                            <label for="id_due_time">Time*</label>
                            <select class="select form-control form-wider" id="id_due_time" name="due_time">
                                <option value="0">12:00 AM</option>
                                <option value="1">1:00 AM</option>
                                <option value="2">2:00 AM</option>
                                <option value="3">3:00 AM</option>
                                <option value="4">4:00 AM</option>
                                <option value="5">5:00 AM</option>
                                <option value="6">6:00 AM</option>
                                <option value="7">7:00 AM</option>
                                <option value="8">8:00 AM</option>
                                <option value="9">9:00 AM</option>
                                <option value="10">10:00 AM</option>
                                <option value="11">11:00 AM</option>
                                <option value="12" selected='selected'>12:00 PM</option>
                                <option value="13">1:00 PM</option>
                                <option value="14">2:00 PM</option>
                                <option value="15">3:00 PM</option>
                                <option value="16">4:00 PM</option>
                                <option value="17">5:00 PM</option>
                                <option value="18">6:00 PM</option>
                                <option value="19">7:00 PM</option>
                                <option value="20">8:00 PM</option>
                                <option value="21">9:00 PM</option>
                                <option value="22">10:00 PM</option>
                                <option value="23">11:00 PM</option>
                            </select>
                        </div>
                    </div>

                    <div id="div_choice_frequency" class="form-group" style="display: none;">
                        <div id="div_id_frequency_int" class="form-group">
                            <label for="id_frequency_int">Once Every*</label>
                            <input class="numberinput form-control form-wider" id="id_frequency_int" min="1" name="frequency_int" type="number" placeholder="Once Every" onkeypress="return isNumber(event)">
                        </div>
                        <div id="div_id_frequency_choice" class="ui-field-contain">
                            <label for="id_frequency_choice">Frequency*</label>
                            <select class="select form-control form-wider" id="id_frequency_choice" name="frequency_choice">
                                <option value="1">Hour(s)</option>
                                <option value="2" selected='selected'>Day(s)</option>
                                <option value="3">Week(s)</option>
                                <option value="4">Month(s)</option>
                                <option value="5">Year(s)</option>
                            </select>
                        </div>
                    </div>

                    <div id="div_id_importance" class="ui-field-contain">
                        <label for="id_importance">Importance</label>
                        <select class="select form-control form-match" id="id_importance" name="importance">
                            <option value="1">Trivial</option>
                            <option value="2">Minor</option>
                            <option value="3" selected='selected'>Moderate</option>
                            <option value="4">Significant</option>
                            <option value="5">Critical</option>
                        </select>
                    </div>

                    <div id="div_id_category" class="ui-field-contain">
                        <label for="id_category">Category*</label>
                        <select id="id_category" name="category">
                            {% for category in category_list %}<option value="{{ category.value }}"{% if category.name == 'General' %} selected='selected'{% endif %}>{{ category }}</option>
                            {% endfor %}
                        </select>
                    </div>



